# Generated by Django 4.1.5 on 2023-03-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
