# Generated by Django 4.1.5 on 2023-03-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0002_rename_departments_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
    ]
