# Generated by Django 4.1.5 on 2023-03-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0003_rename_department_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
