# Generated by Django 4.1.5 on 2023-03-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doct', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_phone', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doct.doctors')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
